controller_manager:
  ros__parameters:
    update_rate: 10 # Hz

    arm_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_6 # joint_6 is a fake joint for controlling suction gripper

    command_interfaces:
      - position

    state_interfaces:
      - position